name: Elixir Quality Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  quality_checks:
    name: Elixir Quality Checks
    runs-on: ubuntu-24.04
    env:
      # In MIX_ENV=test, `$ mix xref graph` shows us a whole bunch of
      # test stuff that isn't really relevant.
      # The other checks don't really care what environment they run in.
      MIX_ENV: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2.4
          elixir-version: 1.18.2
          install-hex: true

      - name: Install dependencies
        run: mix deps.get

      - name: Check for unused deps
        run: mix deps.unlock --check-unused

      - name: Check code formatting
        run: mix format --check-formatted
        # We run all checks here even if others failed so that
        # we give devs as much feedback as possible & save some time.
        if: always()

      - name: Check for compile-time dependencies between modules
        run: mix xref graph --label compile-connected --fail-above 0
        if: always()
