name: Elixir Retired Packages Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  retired_packages:
    name: Elixir Retired Packages Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup beam
        uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2.4
          elixir-version: 1.18.2
          install-hex: true

      - name: Install dependencies
        run: mix deps.get

      - name: Check for retired/abandoned deps
        run: mix hex.audit
